export const ridings = [ 'Burnaby North',
  'Port Moody-Coquitlam',
  'Peace River North',
  'Richmond-Queensborough',
  'Surrey South',
  'Surrey-Guildford (Surrey-Tynehead)',
  'Surrey-Fleetwood',
  'Delta North',
  'Maple Ridge-Mission',
  'Vancouver-Fraserview',
  'Penticton',
  'North Vancouver-Lonsdale',
  'Courtenay-Comox (Comox Valley)',
  'Coquitlam-Maillardville',
  'Maple Ridge-Pitt Meadows',
  'Saanich North and the Islands',
  'Burnaby-Deer Lake',
  'Burnaby-Lougheed',
  'Peace River South',
  'Cariboo North',
  'Skeena',
  'Kelowna West (By election)',
  'Kootenay East',
  'Kamloops-North Thompson',
  'Fraser-Nicola',
  'Boundary-Similkameen',
  'Surrey-Panorama',
  'Abbotsford South',
  'Chilliwack',
  'Vancouver-Fairview',
  'Vancouver-Langara',
  'Vancouver-Kensington',
  'Burnaby-Edmonds',
  'Coquitlam-Burke Mountain (By election)',
  'Port Coquitlam',
  'New Westminster',
  'Prince George-Valemount',
  'Prince George-Mackenzie',
  'Nechako Lakes',
  'North Coast',
  'Cariboo-Chilcotin',
  'Stikine',
  'Richmond North Centre (Richmond Centre)',
  'Richmond South Centre (Richmond East)',
  'Richmond-Steveston',
  'West Vancouver-Sea to Sky',
  'West Vancouver-Capilano',
  'North Vancouver-Seymour',
  'Columbia River-Revelstoke',
  'Kelowna-Lake Country',
  'Kelowna-Mission',
  'Vernon-Monashee',
  'Kootenay West',
  'Shuswap',
  'Nelson-Creston',
  'Kamloops-South Thompson',
  'Surrey-Whalley',
  'Surrey-Green Timbers',
  'Surrey-Newton',
  'Surrey-Cloverdale',
  'Surrey-White Rock',
  'Delta South',
  'Abbotsford-Mission',
  'Chilliwack-Kent (Chilliwack-Hope)',
  'Langley',
  'Abbotsford West',
  'Langley East (Fort Langley-Aldergrove)',
  'Vancouver-Kingsway',
  'Vancouver-Mount Pleasant (By election)',
  'Vancouver-West End',
  'Vancouver-Hastings',
  'Vancouver-Point Grey',
  'Vancouver-False Creek',
  'Vancouver-Quilchena',
  'North Island',
  'Nanaimo',
  'Victoria-Swan Lake',
  'Langford-Juan de Fuca',
  'Mid Island-Pacific Rim (Alberni-Pacific Rim)',
  'Esquimalt-Metchosin (Esquaimalt-Royal Roads)',
  'Victoria-Beacon Hill',
  'Nanaimo-North Cowichan',
  'Cowichan Valley',
  'Powell River-Sunshine Coast',
  'Saanich South',
  'Parksville-Qualicum',
  'Oak Bay-Gordon Head' ]
export const regions = [ 'The North',
  'Cariboo-Thompson',
  'Okanagan',
  'Columbia-Kootenay',
  'Fraser Valley',
  'Tri-Cities',
  'Surrey',
  'Richmond',
  'Delta',
  'Burnaby',
  'New Westminster',
  'Vancouver',
  'North Vancouver',
  'West Vancouver',
  'Vancouver Island and South Coast',
  'Prince George',
  'Peace River',
  'Maple Ridge',
  'Chilliwack',
  'Abbostford',
  'Langley',
  'Kamloops',
  'Port Moody',
  'Coquitlam',
  'Victoria',
  'Nainaimo' ]
