export const ridings = [ 'Abbotsford South', 
'Abbotsford West', 
'Abbotsford-Mission', 
'Boundary-Similkameen', 
'Burnaby North', 
'Burnaby-Deer Lake', 
'Burnaby-Edmonds', 
'Burnaby-Lougheed', 
'Cariboo North', 
'Cariboo-Chilcotin', 
'Chilliwack', 
'Chilliwack-Kent (Chilliwack-Hope)', 
'Columbia River-Revelstoke', 
'Coquitlam-Burke Mountain (By election)', 
'Coquitlam-Maillardville', 
'Courtenay-Comox (Comox Valley)', 
'Cowichan Valley', 
'Delta North', 
'Delta South', 
'Esquimalt-Metchosin (Esquaimalt-Royal Roads)', 
'Fraser-Nicola', 
'Kamloops-North Thompson', 
'Kamloops-South Thompson', 
'Kelowna West (By election)', 
'Kelowna-Lake Country', 
'Kelowna-Mission', 
'Kootenay East', 
'Kootenay West', 
'Langford-Juan de Fuca', 
'Langley', 
'Langley East (Fort Langley-Aldergrove)', 
'Maple Ridge-Mission', 
'Maple Ridge-Pitt Meadows', 
'Mid Island-Pacific Rim (Alberni-Pacific Rim)', 
'Nanaimo', 
'Nanaimo-North Cowichan', 
'Nechako Lakes', 
'Nelson-Creston', 
'New Westminster', 
'North Coast', 
'North Island', 
'North Vancouver-Lonsdale', 
'North Vancouver-Seymour', 
'Oak Bay-Gordon Head', 
'Parksville-Qualicum', 
'Peace River North', 
'Peace River South', 
'Penticton', 
'Port Coquitlam', 
'Port Moody-Coquitlam', 
'Powell River-Sunshine Coast', 
'Prince George-Mackenzie', 
'Prince George-Valemount', 
'Richmond North Centre (Richmond Centre)', 
'Richmond South Centre (Richmond East)', 
'Richmond-Queensborough', 
'Richmond-Steveston', 
'Saanich North and the Islands', 
'Saanich South', 
'Shuswap', 
'Skeena', 
'Stikine', 
'Surrey South', 
'Surrey-Cloverdale', 
'Surrey-Fleetwood', 
'Surrey-Green Timbers', 
'Surrey-Guildford (Surrey-Tynehead)', 
'Surrey-Newton', 
'Surrey-Panorama', 
'Surrey-Whalley', 
'Surrey-White Rock', 
'Vancouver-Fairview', 
'Vancouver-False Creek', 
'Vancouver-Fraserview', 
'Vancouver-Hastings', 
'Vancouver-Kensington', 
'Vancouver-Kingsway', 
'Vancouver-Langara', 
'Vancouver-Mount Pleasant (By election)', 
'Vancouver-Point Grey', 
'Vancouver-Quilchena', 
'Vancouver-West End', 
'Vernon-Monashee', 
'Victoria-Beacon Hill', 
'Victoria-Swan Lake', 
'West Vancouver-Capilano', 
'West Vancouver-Sea to Sky']
export const regions = [ 'Abbostford', 
'Burnaby', 
'Cariboo-Thompson', 
'Chilliwack', 
'Columbia-Kootenay', 
'Coquitlam', 
'Delta', 
'Fraser Valley', 
'Kamloops', 
'Langley', 
'Maple Ridge', 
'Nainaimo', 
'New Westminster', 
'North Vancouver', 
'Okanagan', 
'Peace River', 
'Port Moody', 
'Prince George', 
'Richmond', 
'Surrey', 
'The North', 
'Tri-Cities', 
'Vancouver', 
'Vancouver Island and South Coast', 
'Victoria', 
'West Vancouver']
